server:
  port: 8888
spring:
  application:
    name: server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EternalJourneyman1/spring-cloud-config-server-repo
          default-label: main
          clone-on-start: true
        bootstrap: true
  profiles:
    active: development
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"