server:
  port: 8888
spring:
  application:
    name: server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EternalJourneyman1/spring-cloud-config-server-repo
          default-label: master
          clone-on-start: true
        bootstrap: true
  profiles:
    active: development